// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// 统计概览：7 天内有设备活跃的用户数
	CountActiveUsersSince(ctx context.Context, lastActiveAt pgtype.Timestamptz) (int64, error)
	CountTotalDevices(ctx context.Context) (int64, error)
	CountUserDevices(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// 禁用用户时吊销全部设备
	DeleteAllUserDevices(ctx context.Context, userID string) error
	DeleteDevice(ctx context.Context, deviceID string) error
	// ============================================================
	// system_configs 查询（加密配置）
	// 使用服务：全部 4 个服务（通过 ConfigService 访问）
	// ============================================================
	GetConfig(ctx context.Context, key string) (SystemConfig, error)
	// ============================================================
	// devices 查询
	// 使用服务：auth-svc, admin-svc
	// ============================================================
	GetDeviceByDeviceID(ctx context.Context, deviceID string) (Device, error)
	// auth/refresh 时同时取用户 role
	GetDeviceWithUser(ctx context.Context, deviceID string) (GetDeviceWithUserRow, error)
	// MAX_DEVICES 超限时踢出最老设备
	GetOldestDevice(ctx context.Context, userID string) (Device, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// ============================================================
	// users 查询
	// 使用服务：auth-svc, sync-svc, admin-svc, proxy-svc（disabled 检查）
	// ============================================================
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// ConfigService.Preload 启动时预热所有配置
	ListAllConfigs(ctx context.Context) ([]SystemConfig, error)
	ListUserDevices(ctx context.Context, userID string) ([]Device, error)
	// Admin 分页查询，支持手机号前缀搜索
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	UpdateDeviceLastActive(ctx context.Context, deviceID string) error
	// RT 轮换后更新 hash 和活跃时间
	UpdateDeviceRT(ctx context.Context, arg UpdateDeviceRTParams) error
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) (SystemConfig, error)
	// 登录时写入或更新设备信息（rt_hash, platform, last_active_at）
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	// 幂等创建/更新（SMS 验证通过后调用）
	UpsertUser(ctx context.Context, phone string) (User, error)
}

var _ Querier = (*Queries)(nil)
