// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsersSince = `-- name: CountActiveUsersSince :one
SELECT COUNT(DISTINCT d.user_id)
FROM devices d
WHERE d.last_active_at >= $1
`

// 统计概览：7 天内有设备活跃的用户数
func (q *Queries) CountActiveUsersSince(ctx context.Context, lastActiveAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersSince, lastActiveAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, role, disabled, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one

SELECT id, phone, role, disabled, created_at, updated_at FROM users WHERE phone = $1
`

// ============================================================
// users 查询
// 使用服务：auth-svc, sync-svc, admin-svc, proxy-svc（disabled 检查）
// ============================================================
func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
  u.id, u.phone, u.role, u.disabled, u.created_at, u.updated_at,
  COUNT(d.id) AS device_count
FROM users u
LEFT JOIN devices d ON d.user_id = u.id
WHERE ($3::text = '' OR u.phone LIKE $3 || '%')
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Phone  string `json:"phone"`
}

type ListUsersRow struct {
	ID          string             `json:"id"`
	Phone       string             `json:"phone"`
	Role        UserRole           `json:"role"`
	Disabled    bool               `json:"disabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeviceCount int64              `json:"device_count"`
}

// Admin 分页查询，支持手机号前缀搜索
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.Phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users
SET disabled = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserDisabledParams struct {
	ID       string `json:"id"`
	Disabled bool   `json:"disabled"`
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.Disabled)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserRoleParams struct {
	ID   string   `json:"id"`
	Role UserRole `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (phone)
VALUES ($1)
ON CONFLICT (phone) DO UPDATE
  SET updated_at = NOW()
RETURNING id, phone, role, disabled, created_at, updated_at
`

// 幂等创建/更新（SMS 验证通过后调用）
func (q *Queries) UpsertUser(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
