import 'package:isar/isar.dart';

part 'cached_response.g.dart';

/// Isar collection for stale-while-revalidate response cache (L2).
@collection
class CachedResponse {
  Id id = Isar.autoIncrement;

  /// Stable key: URL + sorted-parameter hash (generated by CachePolicy).
  @Index(unique: true)
  late String cacheKey;

  late String body;        // JSON string
  late String etag;
  late DateTime cachedAt;
  late int ttlSeconds;

  @ignore
  bool get isExpired =>
      DateTime.now().isAfter(cachedAt.add(Duration(seconds: ttlSeconds)));
}
