// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package repo

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users
`

// 初始化检查：count > 0 表示已初始化
func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (username, password_hash, role, totp_secret)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, role, totp_secret, disabled, created_at
`

type CreateAdminParams struct {
	Username     string   `json:"username"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
	TotpSecret   *string  `json:"totp_secret"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.TotpSecret,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, role, totp_secret, disabled, created_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one

SELECT id, username, password_hash, role, totp_secret, disabled, created_at FROM admin_users WHERE username = $1
`

// ============================================================
// admin_users 查询
// 使用服务：admin-svc
// ============================================================
func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, role, totp_secret, disabled, created_at FROM admin_users ORDER BY created_at ASC
`

func (q *Queries) ListAdmins(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminUser
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.TotpSecret,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminDisabled = `-- name: SetAdminDisabled :exec
UPDATE admin_users SET disabled = $2 WHERE id = $1
`

type SetAdminDisabledParams struct {
	ID       string `json:"id"`
	Disabled bool   `json:"disabled"`
}

func (q *Queries) SetAdminDisabled(ctx context.Context, arg SetAdminDisabledParams) error {
	_, err := q.db.Exec(ctx, setAdminDisabled, arg.ID, arg.Disabled)
	return err
}

const upsertAdmin = `-- name: UpsertAdmin :one
INSERT INTO admin_users (username, password_hash, role)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      role          = EXCLUDED.role,
      disabled      = FALSE
RETURNING id, username, password_hash, role, totp_secret, disabled, created_at
`

type UpsertAdminParams struct {
	Username     string   `json:"username"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

// CLI reset-admin 工具使用：若用户名已存在则更新密码和角色
func (q *Queries) UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, upsertAdmin, arg.Username, arg.PasswordHash, arg.Role)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}
