// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTotalDevices = `-- name: CountTotalDevices :one
SELECT COUNT(*) FROM devices
`

func (q *Queries) CountTotalDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserDevices = `-- name: CountUserDevices :one
SELECT COUNT(*) FROM devices WHERE user_id = $1
`

func (q *Queries) CountUserDevices(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllUserDevices = `-- name: DeleteAllUserDevices :exec
DELETE FROM devices WHERE user_id = $1
`

// 禁用用户时吊销全部设备
func (q *Queries) DeleteAllUserDevices(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllUserDevices, userID)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE device_id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, deleteDevice, deviceID)
	return err
}

const getDeviceByDeviceID = `-- name: GetDeviceByDeviceID :one

SELECT id, user_id, device_id, platform, rt_hash, last_active_at, created_at FROM devices WHERE device_id = $1
`

// ============================================================
// devices 查询
// 使用服务：auth-svc, admin-svc
// ============================================================
func (q *Queries) GetDeviceByDeviceID(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByDeviceID, deviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.RtHash,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceWithUser = `-- name: GetDeviceWithUser :one
SELECT d.id, d.user_id, d.device_id, d.platform, d.rt_hash, d.last_active_at, d.created_at, u.role AS user_role, u.disabled AS user_disabled
FROM devices d
JOIN users u ON u.id = d.user_id
WHERE d.device_id = $1
`

type GetDeviceWithUserRow struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	DeviceID     string             `json:"device_id"`
	Platform     string             `json:"platform"`
	RtHash       string             `json:"rt_hash"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserRole     UserRole           `json:"user_role"`
	UserDisabled bool               `json:"user_disabled"`
}

// auth/refresh 时同时取用户 role
func (q *Queries) GetDeviceWithUser(ctx context.Context, deviceID string) (GetDeviceWithUserRow, error) {
	row := q.db.QueryRow(ctx, getDeviceWithUser, deviceID)
	var i GetDeviceWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.RtHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UserRole,
		&i.UserDisabled,
	)
	return i, err
}

const getOldestDevice = `-- name: GetOldestDevice :one
SELECT id, user_id, device_id, platform, rt_hash, last_active_at, created_at FROM devices
WHERE user_id = $1
ORDER BY last_active_at ASC
LIMIT 1
`

// MAX_DEVICES 超限时踢出最老设备
func (q *Queries) GetOldestDevice(ctx context.Context, userID string) (Device, error) {
	row := q.db.QueryRow(ctx, getOldestDevice, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.RtHash,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT id, user_id, device_id, platform, rt_hash, last_active_at, created_at FROM devices WHERE user_id = $1 ORDER BY last_active_at DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Platform,
			&i.RtHash,
			&i.LastActiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceLastActive = `-- name: UpdateDeviceLastActive :exec
UPDATE devices
SET last_active_at = NOW()
WHERE device_id = $1
`

func (q *Queries) UpdateDeviceLastActive(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, updateDeviceLastActive, deviceID)
	return err
}

const updateDeviceRT = `-- name: UpdateDeviceRT :exec
UPDATE devices
SET rt_hash        = $2,
    last_active_at = NOW()
WHERE device_id = $1
`

type UpdateDeviceRTParams struct {
	DeviceID string `json:"device_id"`
	RtHash   string `json:"rt_hash"`
}

// RT 轮换后更新 hash 和活跃时间
func (q *Queries) UpdateDeviceRT(ctx context.Context, arg UpdateDeviceRTParams) error {
	_, err := q.db.Exec(ctx, updateDeviceRT, arg.DeviceID, arg.RtHash)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, device_id, platform, rt_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (device_id) DO UPDATE
  SET rt_hash        = EXCLUDED.rt_hash,
      platform       = EXCLUDED.platform,
      last_active_at = NOW()
RETURNING id, user_id, device_id, platform, rt_hash, last_active_at, created_at
`

type UpsertDeviceParams struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Platform string `json:"platform"`
	RtHash   string `json:"rt_hash"`
}

// 登录时写入或更新设备信息（rt_hash, platform, last_active_at）
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.UserID,
		arg.DeviceID,
		arg.Platform,
		arg.RtHash,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.RtHash,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}
