// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// 统计概览：7 天内有设备活跃的用户数
	CountActiveUsersSince(ctx context.Context, lastActiveAt pgtype.Timestamptz) (int64, error)
	// 初始化检查：count > 0 表示已初始化
	CountAdminUsers(ctx context.Context) (int64, error)
	CountOperationLogs(ctx context.Context, action string) (int64, error)
	CountTotalDevices(ctx context.Context) (int64, error)
	CountUserDevices(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error)
	// ============================================================
	// operation_logs 查询（追加写，不可修改/删除）
	// 使用服务：admin-svc（写）、admin-svc（读查询）
	// ============================================================
	CreateOperationLog(ctx context.Context, arg CreateOperationLogParams) (OperationLog, error)
	// 禁用用户时吊销全部设备
	DeleteAllUserDevices(ctx context.Context, userID string) error
	DeleteDevice(ctx context.Context, deviceID string) error
	GetAdminByID(ctx context.Context, id string) (AdminUser, error)
	// ============================================================
	// admin_users 查询
	// 使用服务：admin-svc
	// ============================================================
	GetAdminByUsername(ctx context.Context, username string) (AdminUser, error)
	// ============================================================
	// system_configs 查询（加密配置）
	// 使用服务：全部 4 个服务（通过 ConfigService 访问）
	// ============================================================
	GetConfig(ctx context.Context, key string) (SystemConfig, error)
	// ============================================================
	// devices 查询
	// 使用服务：auth-svc, admin-svc
	// ============================================================
	GetDeviceByDeviceID(ctx context.Context, deviceID string) (Device, error)
	// auth/refresh 时同时取用户 role
	GetDeviceWithUser(ctx context.Context, deviceID string) (GetDeviceWithUserRow, error)
	// MAX_DEVICES 超限时踢出最老设备
	GetOldestDevice(ctx context.Context, userID string) (Device, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// ============================================================
	// users 查询
	// 使用服务：auth-svc, sync-svc, admin-svc, proxy-svc（disabled 检查）
	// ============================================================
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	ListAdmins(ctx context.Context) ([]AdminUser, error)
	// ConfigService.Preload 启动时预热所有配置
	ListAllConfigs(ctx context.Context) ([]SystemConfig, error)
	ListOperationLogs(ctx context.Context, arg ListOperationLogsParams) ([]OperationLog, error)
	ListUserDevices(ctx context.Context, userID string) ([]Device, error)
	// Admin 分页查询，支持手机号前缀搜索
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SetAdminDisabled(ctx context.Context, arg SetAdminDisabledParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	UpdateDeviceLastActive(ctx context.Context, deviceID string) error
	// RT 轮换后更新 hash 和活跃时间
	UpdateDeviceRT(ctx context.Context, arg UpdateDeviceRTParams) error
	// CLI reset-admin 工具使用：若用户名已存在则更新密码和角色
	UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (AdminUser, error)
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) (SystemConfig, error)
	// 登录时写入或更新设备信息（rt_hash, platform, last_active_at）
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	// 幂等创建/更新（SMS 验证通过后调用）
	UpsertUser(ctx context.Context, phone string) (User, error)
}

var _ Querier = (*Queries)(nil)
