// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHistory = `-- name: CountHistory :one
SELECT COUNT(*) FROM history WHERE user_id = $1
`

func (q *Queries) CountHistory(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHistory, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHistory = `-- name: CreateHistory :one

INSERT INTO history (user_id, song_mid, progress)
VALUES ($1, $2, $3)
RETURNING id, user_id, song_mid, progress, played_at
`

type CreateHistoryParams struct {
	UserID   string `json:"user_id"`
	SongMid  string `json:"song_mid"`
	Progress int32  `json:"progress"`
}

// ============================================================
// history 查询
// 使用服务：sync-svc
// ============================================================
func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error) {
	row := q.db.QueryRow(ctx, createHistory, arg.UserID, arg.SongMid, arg.Progress)
	var i History
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SongMid,
		&i.Progress,
		&i.PlayedAt,
	)
	return i, err
}

const getSongProgress = `-- name: GetSongProgress :one
SELECT progress, played_at
FROM history
WHERE user_id = $1 AND song_mid = $2
ORDER BY played_at DESC
LIMIT 1
`

type GetSongProgressParams struct {
	UserID  string `json:"user_id"`
	SongMid string `json:"song_mid"`
}

type GetSongProgressRow struct {
	Progress int32              `json:"progress"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

// 查询指定歌曲的最近一次播放进度
func (q *Queries) GetSongProgress(ctx context.Context, arg GetSongProgressParams) (GetSongProgressRow, error) {
	row := q.db.QueryRow(ctx, getSongProgress, arg.UserID, arg.SongMid)
	var i GetSongProgressRow
	err := row.Scan(&i.Progress, &i.PlayedAt)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT id, user_id, song_mid, progress, played_at FROM history
WHERE user_id = $1
ORDER BY played_at DESC
LIMIT $2 OFFSET $3
`

type ListHistoryParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error) {
	rows, err := q.db.Query(ctx, listHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongMid,
			&i.Progress,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistorySince = `-- name: ListHistorySince :many
SELECT id, user_id, song_mid, progress, played_at FROM history
WHERE user_id = $1 AND played_at > $2
ORDER BY played_at DESC
`

type ListHistorySinceParams struct {
	UserID   string             `json:"user_id"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

// /user/sync?since= 拉取新历史
func (q *Queries) ListHistorySince(ctx context.Context, arg ListHistorySinceParams) ([]History, error) {
	rows, err := q.db.Query(ctx, listHistorySince, arg.UserID, arg.PlayedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongMid,
			&i.Progress,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimHistory = `-- name: TrimHistory :exec
DELETE FROM history AS h1
WHERE h1.id IN (
  SELECT h2.id FROM history AS h2
  WHERE h2.user_id = $1
  ORDER BY h2.played_at DESC
  OFFSET $2
)
`

type TrimHistoryParams struct {
	UserID string `json:"user_id"`
	Offset int32  `json:"offset"`
}

// Delete all but the $2 most recent records for user $1.
func (q *Queries) TrimHistory(ctx context.Context, arg TrimHistoryParams) error {
	_, err := q.db.Exec(ctx, trimHistory, arg.UserID, arg.Offset)
	return err
}

const updateSongProgress = `-- name: UpdateSongProgress :one
INSERT INTO history (user_id, song_mid, progress)
VALUES ($1, $2, $3)
RETURNING id, user_id, song_mid, progress, played_at
`

type UpdateSongProgressParams struct {
	UserID   string `json:"user_id"`
	SongMid  string `json:"song_mid"`
	Progress int32  `json:"progress"`
}

// 插入新记录（历史追加，不 upsert，让 TrimHistory 负责裁剪）
func (q *Queries) UpdateSongProgress(ctx context.Context, arg UpdateSongProgressParams) (History, error) {
	row := q.db.QueryRow(ctx, updateSongProgress, arg.UserID, arg.SongMid, arg.Progress)
	var i History
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SongMid,
		&i.Progress,
		&i.PlayedAt,
	)
	return i, err
}
