// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUSER       UserRole = "USER"
	UserRoleADMIN      UserRole = "ADMIN"
	UserRoleSUPERADMIN UserRole = "SUPER_ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AdminUser struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	TotpSecret   *string            `json:"totp_secret"`
	Disabled     bool               `json:"disabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	DeviceID     string             `json:"device_id"`
	Platform     string             `json:"platform"`
	RtHash       string             `json:"rt_hash"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	TargetID  string             `json:"target_id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type History struct {
	ID       string             `json:"id"`
	UserID   string             `json:"user_id"`
	SongMid  string             `json:"song_mid"`
	Progress int32              `json:"progress"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

type OperationLog struct {
	ID        string             `json:"id"`
	AdminID   string             `json:"admin_id"`
	Action    string             `json:"action"`
	TargetID  *string            `json:"target_id"`
	BeforeVal *string            `json:"before_val"`
	AfterVal  *string            `json:"after_val"`
	Ip        string             `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlaylistSong struct {
	ID         string             `json:"id"`
	PlaylistID string             `json:"playlist_id"`
	SongMid    string             `json:"song_mid"`
	SortOrder  int32              `json:"sort_order"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
}

type SystemConfig struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy string             `json:"updated_by"`
}

type User struct {
	ID        string             `json:"id"`
	Phone     string             `json:"phone"`
	Role      UserRole           `json:"role"`
	Disabled  bool               `json:"disabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserPlaylist struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
