// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) (PlaylistSong, error)
	// 删除歌曲后，将 sort_order 大于被删位置的记录减 1
	CompactSortOrder(ctx context.Context, arg CompactSortOrderParams) error
	// 统计概览：7 天内有设备活跃的用户数
	CountActiveUsersSince(ctx context.Context, lastActiveAt pgtype.Timestamptz) (int64, error)
	CountFavorites(ctx context.Context, arg CountFavoritesParams) (int64, error)
	CountHistory(ctx context.Context, userID string) (int64, error)
	CountTotalDevices(ctx context.Context) (int64, error)
	CountUserDevices(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ============================================================
	// favorites 查询（软删除模型）
	// 使用服务：sync-svc
	// ============================================================
	// ON CONFLICT DO NOTHING 保证幂等（重复添加不报错）
	CreateFavorite(ctx context.Context, arg CreateFavoriteParams) (Favorite, error)
	// ============================================================
	// history 查询
	// 使用服务：sync-svc
	// ============================================================
	CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error)
	// ============================================================
	// playlists + playlist_songs 查询
	// 使用服务：sync-svc
	// ============================================================
	// ── user_playlists ──────────────────────────────────────────
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (UserPlaylist, error)
	// 禁用用户时吊销全部设备
	DeleteAllUserDevices(ctx context.Context, userID string) error
	DeleteDevice(ctx context.Context, deviceID string) error
	// ============================================================
	// system_configs 查询（加密配置）
	// 使用服务：全部 4 个服务（通过 ConfigService 访问）
	// ============================================================
	GetConfig(ctx context.Context, key string) (SystemConfig, error)
	// ============================================================
	// devices 查询
	// 使用服务：auth-svc, admin-svc
	// ============================================================
	GetDeviceByDeviceID(ctx context.Context, deviceID string) (Device, error)
	// auth/refresh 时同时取用户 role
	GetDeviceWithUser(ctx context.Context, deviceID string) (GetDeviceWithUserRow, error)
	GetFavoriteByID(ctx context.Context, arg GetFavoriteByIDParams) (Favorite, error)
	GetFavoriteByTarget(ctx context.Context, arg GetFavoriteByTargetParams) (Favorite, error)
	// ── playlist_songs ──────────────────────────────────────────
	// 追加歌曲时获取下一个 sort_order
	GetNextSortOrder(ctx context.Context, playlistID string) (interface{}, error)
	// MAX_DEVICES 超限时踢出最老设备
	GetOldestDevice(ctx context.Context, userID string) (Device, error)
	GetPlaylistByID(ctx context.Context, arg GetPlaylistByIDParams) (UserPlaylist, error)
	GetPlaylistSong(ctx context.Context, arg GetPlaylistSongParams) (PlaylistSong, error)
	// 查询指定歌曲的最近一次播放进度
	GetSongProgress(ctx context.Context, arg GetSongProgressParams) (GetSongProgressRow, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// ============================================================
	// users 查询
	// 使用服务：auth-svc, sync-svc, admin-svc, proxy-svc（disabled 检查）
	// ============================================================
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// ConfigService.Preload 启动时预热所有配置
	ListAllConfigs(ctx context.Context) ([]SystemConfig, error)
	// /user/sync?since= 拉取软删除的收藏 ID
	ListDeletedFavoritesSince(ctx context.Context, arg ListDeletedFavoritesSinceParams) ([]string, error)
	ListDeletedPlaylistsSince(ctx context.Context, arg ListDeletedPlaylistsSinceParams) ([]string, error)
	// 分页；type 为空字符串时查全部类型
	ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]Favorite, error)
	// /user/sync?since= 拉取新增收藏
	ListFavoritesSince(ctx context.Context, arg ListFavoritesSinceParams) ([]Favorite, error)
	ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error)
	// /user/sync?since= 拉取新历史
	ListHistorySince(ctx context.Context, arg ListHistorySinceParams) ([]History, error)
	ListPlaylistSongs(ctx context.Context, playlistID string) ([]PlaylistSong, error)
	// /user/sync?since= 拉取变更歌单
	ListPlaylistsSince(ctx context.Context, arg ListPlaylistsSinceParams) ([]UserPlaylist, error)
	ListUserDevices(ctx context.Context, userID string) ([]Device, error)
	ListUserPlaylists(ctx context.Context, userID string) ([]ListUserPlaylistsRow, error)
	// Admin 分页查询，支持手机号前缀搜索
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) (int32, error)
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	SoftDeleteFavorite(ctx context.Context, arg SoftDeleteFavoriteParams) (Favorite, error)
	SoftDeletePlaylist(ctx context.Context, arg SoftDeletePlaylistParams) error
	// Delete all but the $2 most recent records for user $1.
	TrimHistory(ctx context.Context, arg TrimHistoryParams) error
	UpdateDeviceLastActive(ctx context.Context, deviceID string) error
	// RT 轮换后更新 hash 和活跃时间
	UpdateDeviceRT(ctx context.Context, arg UpdateDeviceRTParams) error
	UpdatePlaylistName(ctx context.Context, arg UpdatePlaylistNameParams) (UserPlaylist, error)
	// 插入新记录（历史追加，不 upsert，让 TrimHistory 负责裁剪）
	UpdateSongProgress(ctx context.Context, arg UpdateSongProgressParams) (History, error)
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) (SystemConfig, error)
	// 登录时写入或更新设备信息（rt_hash, platform, last_active_at）
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	// 幂等创建/更新（SMS 验证通过后调用）
	UpsertUser(ctx context.Context, phone string) (User, error)
}

var _ Querier = (*Queries)(nil)
