// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_configs.sql

package repo

import (
	"context"
)

const getConfig = `-- name: GetConfig :one

SELECT key, value, updated_at, updated_by FROM system_configs WHERE key = $1
`

// ============================================================
// system_configs 查询（加密配置）
// 使用服务：全部 4 个服务（通过 ConfigService 访问）
// ============================================================
func (q *Queries) GetConfig(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAllConfigs = `-- name: ListAllConfigs :many
SELECT key, value, updated_at, updated_by FROM system_configs
`

// ConfigService.Preload 启动时预热所有配置
func (q *Queries) ListAllConfigs(ctx context.Context) ([]SystemConfig, error) {
	rows, err := q.db.Query(ctx, listAllConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemConfig
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO system_configs (key, value, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
  SET value      = EXCLUDED.value,
      updated_at = NOW(),
      updated_by = EXCLUDED.updated_by
RETURNING key, value, updated_at, updated_by
`

type UpsertConfigParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, upsertConfig, arg.Key, arg.Value, arg.UpdatedBy)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
